# version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: escoladesafios-frontend
    # depends_on:
    #   - api
    ports:
      - "3000:3000"
    env_file:
      - .env      
    volumes:
      - ./FrontEnd:/app/frontend
      # - /app/node_modules
    working_dir: /app/frontend
    command: npm run dev 
    